service: puppeteer-ts

provider:
  name: aws
  runtime: nodejs14.x

functions:
  puppeteerFunction:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
